# Source data for the 10 Acuven Shop store themes (hand-authored).
# gen.py checks contrast and derives the rest.

KEYS = [
    "surface",
    "surface-alt",
    "surface-raised",
    "tile",
    "tile-alt",
    "ink",
    "ink-muted",
    "rule",
    "border",
    "accent",
    "demo",
    "on-demo",
    "demo-soft",
    "on-demo-soft",
    "demo-mark",
    "banner",
    "banner-2",
    "on-banner",
    "footer",
    "on-footer",
]

STATUS = {
    "light": {
        "success": "#1f7a4a",
        "success-soft": "#dcf0e3",
        "on-success-soft": "#145233",
        "danger": "#b3261e",
        "danger-soft": "#fbe0dd",
        "on-danger-soft": "#7a1a14",
    },
    "dark": {
        "success": "#78d39c",
        "success-soft": "#173524",
        "on-success-soft": "#c3eed3",
        "danger": "#ff8f86",
        "danger-soft": "#3d1a17",
        "on-danger-soft": "#ffd2cd",
    },
}

THEMES = [
    {
        "id": "pandan",
        "hero_shape": "999px 999px 0 0",
        "name": "Pandan",
        "zh": "班兰",
        "fit": "生活方式、家居",
        "fonts": {"display": "Instrument Serif", "body": "Manrope", "num": "Manrope"},
        "display_weight": 400,
        "display_scale": 1.3,
        "display_tracking": "0em",
        "radius": {"control": 6, "card": 6, "tile": 4, "button": 6},
        "border_w": 1,
        "banner": "solid",
        "light": {
            "surface": "#f1f3ef",
            "surface-alt": "#e3e9e1",
            "surface-raised": "#fafbf8",
            "tile": "#dbe3d8",
            "tile-alt": "#efe2dc",
            "ink": "#1f2b24",
            "ink-muted": "#526158",
            "rule": "#d3dbd1",
            "border": "#86968b",
            "accent": "#2f5d46",
            "demo": "#d98c84",
            "on-demo": "#3b1611",
            "demo-soft": "#f6e3df",
            "on-demo-soft": "#5a2a24",
            "demo-mark": "#9c4a40",
            "banner": "#2f5d46",
            "banner-2": "#2f5d46",
            "on-banner": "#eef3ec",
            "footer": "#e3e9e1",
            "on-footer": "#1f2b24",
        },
        "dark": {
            "surface": "#131a16",
            "surface-alt": "#1a241e",
            "surface-raised": "#1f2b24",
            "tile": "#223029",
            "tile-alt": "#33251f",
            "ink": "#e4ebe5",
            "ink-muted": "#a1b0a6",
            "rule": "#2c3a32",
            "border": "#66786c",
            "accent": "#8fc3a6",
            "demo": "#e8a79f",
            "on-demo": "#3b1611",
            "demo-soft": "#3a2420",
            "on-demo-soft": "#f6d4ce",
            "demo-mark": "#eba89f",
            "banner": "#1f3b2d",
            "banner-2": "#1f3b2d",
            "on-banner": "#dfeee4",
            "footer": "#0d1310",
            "on-footer": "#dfe7e1",
        },
        "accents": [
            ("pandan", "Pandan green", "#2f5d46"),
            ("teal", "Teal", "#1f6a66"),
            ("clay", "Clay", "#9a4a36"),
            ("aubergine", "Aubergine", "#6b3b5c"),
            ("charcoal", "Charcoal", "#2b2f2d"),
        ],
    },
    {
        "id": "pasar",
        "hero_shape": "32px",
        "name": "Pasar Pagi",
        "zh": "早市",
        "fit": "日用杂货、社区店",
        "fonts": {"display": "Bricolage Grotesque", "body": "Onest", "num": "Onest"},
        "display_weight": 800,
        "display_scale": 1.0,
        "display_tracking": "-0.02em",
        "radius": {"control": 999, "card": 24, "tile": 28, "button": 999},
        "border_w": 1.5,
        "banner": "stripes",
        "light": {
            "surface": "#fbfaf6",
            "surface-alt": "#edf3ec",
            "surface-raised": "#ffffff",
            "tile": "#e2ebe0",
            "tile-alt": "#fff0c2",
            "ink": "#123c38",
            "ink-muted": "#48645f",
            "rule": "#dbe2d9",
            "border": "#7f958f",
            "accent": "#0f5c52",
            "demo": "#f5b400",
            "on-demo": "#1d1600",
            "demo-soft": "#fff3cc",
            "on-demo-soft": "#3d2f00",
            "demo-mark": "#9a6c00",
            "banner": "#f5b400",
            "banner-2": "#ffc933",
            "on-banner": "#1d1600",
            "footer": "#123c38",
            "on-footer": "#eaf2ee",
        },
        "dark": {
            "surface": "#0e1c1a",
            "surface-alt": "#142826",
            "surface-raised": "#132b28",
            "tile": "#1a3431",
            "tile-alt": "#3a3010",
            "ink": "#e6efea",
            "ink-muted": "#9db4ad",
            "rule": "#27413d",
            "border": "#5a7a74",
            "accent": "#5cc2ab",
            "demo": "#f5b400",
            "on-demo": "#1d1600",
            "demo-soft": "#342a0c",
            "on-demo-soft": "#ffe6a0",
            "demo-mark": "#f5b400",
            "banner": "#f5b400",
            "banner-2": "#e0a400",
            "on-banner": "#1d1600",
            "footer": "#081412",
            "on-footer": "#d6e4de",
        },
        "accents": [
            ("green", "Market green", "#0f5c52"),
            ("tomato", "Tomato", "#b8452a"),
            ("blue", "Harbour blue", "#1f5fa8"),
            ("plum", "Plum", "#7a3b69"),
            ("ink", "Ink", "#1d2321"),
        ],
    },
    {
        "id": "receipt",
        "hero_shape": "0",
        "name": "Receipt",
        "zh": "小票",
        "fit": "数码配件、工具",
        "fonts": {"display": "IBM Plex Sans", "body": "IBM Plex Sans", "num": "IBM Plex Mono"},
        "display_weight": 600,
        "display_scale": 1.05,
        "display_tracking": "-0.035em",
        "radius": {"control": 2, "card": 2, "tile": 0, "button": 2},
        "border_w": 1,
        "banner": "solid",
        "light": {
            "surface": "#f6f6f4",
            "surface-alt": "#ecece9",
            "surface-raised": "#ffffff",
            "tile": "#e7e7e3",
            "tile-alt": "#dcdcd7",
            "ink": "#18181a",
            "ink-muted": "#5a5a60",
            "rule": "#d4d4d0",
            "border": "#18181a",
            "accent": "#18181a",
            "demo": "#ff5b2e",
            "on-demo": "#18181a",
            "demo-soft": "#ffe4da",
            "on-demo-soft": "#6b1f06",
            "demo-mark": "#c23a12",
            "banner": "#18181a",
            "banner-2": "#18181a",
            "on-banner": "#f0f0ee",
            "footer": "#18181a",
            "on-footer": "#f0f0ee",
        },
        "dark": {
            "surface": "#121213",
            "surface-alt": "#19191b",
            "surface-raised": "#1c1c1e",
            "tile": "#232326",
            "tile-alt": "#2c2c30",
            "ink": "#ececea",
            "ink-muted": "#a2a2a8",
            "rule": "#333337",
            "border": "#ececea",
            "accent": "#ececea",
            "demo": "#ff6a3d",
            "on-demo": "#121213",
            "demo-soft": "#3a1a10",
            "on-demo-soft": "#ffc9b5",
            "demo-mark": "#ff8a63",
            "banner": "#2a2a2d",
            "banner-2": "#2a2a2d",
            "on-banner": "#ececea",
            "footer": "#050506",
            "on-footer": "#ececea",
        },
        "accents": [
            ("ink", "Ink", "#18181a"),
            ("cobalt", "Cobalt", "#2340a8"),
            ("forest", "Forest", "#1f5b3a"),
            ("oxblood", "Oxblood", "#7d1f2b"),
        ],
    },
    {
        "id": "kopitiam",
        "hero_shape": "999px 999px 10px 10px",
        "name": "Kopitiam",
        "zh": "咖啡店",
        "fit": "食品、饮料、烘焙",
        "fonts": {"display": "Young Serif", "body": "Figtree", "num": "Figtree"},
        "display_weight": 400,
        "display_scale": 1.0,
        "display_tracking": "-0.01em",
        "radius": {"control": 8, "card": 10, "tile": 10, "button": 8},
        "border_w": 1.5,
        "banner": "solid",
        "light": {
            "surface": "#f6f2ec",
            "surface-alt": "#ece3d6",
            "surface-raised": "#fffdf9",
            "tile": "#e8dccb",
            "tile-alt": "#d9e8df",
            "ink": "#2b1d14",
            "ink-muted": "#6b5647",
            "rule": "#e2d6c5",
            "border": "#9c8674",
            "accent": "#5a3522",
            "demo": "#e2572f",
            "on-demo": "#2b0f06",
            "demo-soft": "#fbe1d6",
            "on-demo-soft": "#6e2410",
            "demo-mark": "#b83d1c",
            "banner": "#1f6b52",
            "banner-2": "#1f6b52",
            "on-banner": "#f3efe6",
            "footer": "#2b1d14",
            "on-footer": "#f3e8da",
        },
        "dark": {
            "surface": "#1a130f",
            "surface-alt": "#231a14",
            "surface-raised": "#2a1f18",
            "tile": "#33261d",
            "tile-alt": "#1d3129",
            "ink": "#f3e8da",
            "ink-muted": "#c1ab96",
            "rule": "#3a2c22",
            "border": "#7d6655",
            "accent": "#d9a57b",
            "demo": "#f07a55",
            "on-demo": "#2b0f06",
            "demo-soft": "#3d1d13",
            "on-demo-soft": "#ffd0bf",
            "demo-mark": "#f59a7c",
            "banner": "#174f3d",
            "banner-2": "#174f3d",
            "on-banner": "#e6f2ec",
            "footer": "#0f0a07",
            "on-footer": "#eadccb",
        },
        "accents": [
            ("kopi", "Kopi brown", "#5a3522"),
            ("teh", "Teh tarik", "#8a5a2b"),
            ("tile", "Tile green", "#1f6b52"),
            ("red", "Signboard red", "#9e2a1e"),
        ],
    },
    {
        "id": "batik",
        "hero_shape": "8px",
        "name": "Batik",
        "zh": "蜡染",
        "fit": "手工艺、传统服饰",
        "fonts": {"display": "DM Serif Display", "body": "Work Sans", "num": "Work Sans"},
        "display_weight": 400,
        "display_scale": 1.15,
        "display_tracking": "0em",
        "radius": {"control": 4, "card": 8, "tile": 8, "button": 4},
        "border_w": 1,
        "banner": "solid",
        "light": {
            "surface": "#f4f3f7",
            "surface-alt": "#e6e5ef",
            "surface-raised": "#ffffff",
            "tile": "#dfdeeb",
            "tile-alt": "#f1e3c7",
            "ink": "#1c1b3a",
            "ink-muted": "#55546e",
            "rule": "#d9d8e4",
            "border": "#8583a0",
            "accent": "#2b2d7c",
            "demo": "#d9962b",
            "on-demo": "#241400",
            "demo-soft": "#f7e6c6",
            "on-demo-soft": "#5c3a06",
            "demo-mark": "#8f5d0e",
            "banner": "#2b2d7c",
            "banner-2": "#2b2d7c",
            "on-banner": "#f1f0fa",
            "footer": "#1c1b3a",
            "on-footer": "#ecebf5",
        },
        "dark": {
            "surface": "#12121f",
            "surface-alt": "#1a1a2c",
            "surface-raised": "#202036",
            "tile": "#262640",
            "tile-alt": "#3a2c14",
            "ink": "#ecebf5",
            "ink-muted": "#a9a8c4",
            "rule": "#2e2e48",
            "border": "#6c6b8e",
            "accent": "#9fa3f0",
            "demo": "#e6a948",
            "on-demo": "#241400",
            "demo-soft": "#3a2a10",
            "on-demo-soft": "#f8deb0",
            "demo-mark": "#e6a948",
            "banner": "#22246a",
            "banner-2": "#22246a",
            "on-banner": "#ecebff",
            "footer": "#0b0b16",
            "on-footer": "#e2e1f0",
        },
        "accents": [
            ("indigo", "Indigo", "#2b2d7c"),
            ("sogan", "Sogan brown", "#6b4226"),
            ("maroon", "Maroon", "#7c2335"),
            ("teal", "Deep teal", "#1d5f63"),
        ],
    },
    {
        "id": "malam",
        "hero_shape": "999px 999px 16px 16px",
        "name": "Pasar Malam",
        "zh": "夜市",
        "fit": "潮流、零食、年轻客群",
        "fonts": {"display": "Unbounded", "body": "Rubik", "num": "Rubik"},
        "display_weight": 700,
        "display_scale": 0.85,
        "display_tracking": "-0.02em",
        "radius": {"control": 10, "card": 16, "tile": 16, "button": 999},
        "border_w": 1.5,
        "banner": "stripes",
        "light": {
            "surface": "#f7f2f8",
            "surface-alt": "#efe4f1",
            "surface-raised": "#ffffff",
            "tile": "#eadbee",
            "tile-alt": "#d8f1f0",
            "ink": "#25142e",
            "ink-muted": "#5e4b66",
            "rule": "#e3d4e7",
            "border": "#8f7a98",
            "accent": "#c2186b",
            "demo": "#19c3c3",
            "on-demo": "#06201f",
            "demo-soft": "#d3f3f2",
            "on-demo-soft": "#0b4645",
            "demo-mark": "#0b7a78",
            "banner": "#19c3c3",
            "banner-2": "#3fd6d6",
            "on-banner": "#06201f",
            "footer": "#25142e",
            "on-footer": "#f2e6f5",
        },
        "dark": {
            "surface": "#140b1c",
            "surface-alt": "#1c1026",
            "surface-raised": "#231531",
            "tile": "#2c1a3c",
            "tile-alt": "#0f2e33",
            "ink": "#f4e9fa",
            "ink-muted": "#b9a3c6",
            "rule": "#33204a",
            "border": "#7b6390",
            "accent": "#ff4fa3",
            "demo": "#3be0dc",
            "on-demo": "#04201f",
            "demo-soft": "#0e3033",
            "on-demo-soft": "#b6f5f3",
            "demo-mark": "#3be0dc",
            "banner": "#3be0dc",
            "banner-2": "#22c7c3",
            "on-banner": "#04201f",
            "footer": "#0b0612",
            "on-footer": "#efdff8",
        },
        "accents": [
            ("pink", "Neon pink", "#c2186b"),
            ("violet", "Violet", "#6b2fd6"),
            ("orange", "Satay orange", "#c44a12"),
            ("lime", "Lime", "#3f7d12"),
        ],
    },
    {
        "id": "gula",
        "hero_shape": "999px",
        "name": "Gula-Gula",
        "zh": "糖果",
        "fit": "儿童用品、甜品",
        "fonts": {"display": "Fredoka", "body": "Nunito", "num": "Nunito"},
        "display_weight": 600,
        "display_scale": 1.0,
        "display_tracking": "0em",
        "radius": {"control": 16, "card": 28, "tile": 32, "button": 999},
        "border_w": 2,
        "banner": "dots",
        "light": {
            "surface": "#fff7fa",
            "surface-alt": "#ffe9f1",
            "surface-raised": "#ffffff",
            "tile": "#ffe1ec",
            "tile-alt": "#d9f5ec",
            "ink": "#3a1830",
            "ink-muted": "#7a5670",
            "rule": "#f3d7e3",
            "border": "#b98aa6",
            "accent": "#c42f6c",
            "demo": "#ffd23f",
            "on-demo": "#3a2a00",
            "demo-soft": "#fff4c7",
            "on-demo-soft": "#5b4300",
            "demo-mark": "#9a7300",
            "banner": "#ffd23f",
            "banner-2": "#ffe27a",
            "on-banner": "#3a2a00",
            "footer": "#ffe9f1",
            "on-footer": "#3a1830",
        },
        "dark": {
            "surface": "#1e1119",
            "surface-alt": "#281722",
            "surface-raised": "#2f1b28",
            "tile": "#3a2131",
            "tile-alt": "#173129",
            "ink": "#ffe8f2",
            "ink-muted": "#d0a9bf",
            "rule": "#3e2536",
            "border": "#8e6780",
            "accent": "#ff8fbd",
            "demo": "#ffd23f",
            "on-demo": "#3a2a00",
            "demo-soft": "#3b3212",
            "on-demo-soft": "#fff0b3",
            "demo-mark": "#ffd23f",
            "banner": "#ffd23f",
            "banner-2": "#f0c22c",
            "on-banner": "#3a2a00",
            "footer": "#140a10",
            "on-footer": "#f8dbe8",
        },
        "accents": [
            ("pink", "Bubblegum", "#c42f6c"),
            ("mint", "Mint", "#13806a"),
            ("grape", "Grape", "#7a3aa0"),
            ("orange", "Orange", "#c8541a"),
        ],
    },
    {
        "id": "galeri",
        "hero_shape": "0",
        "name": "Galeri",
        "zh": "画廊",
        "fit": "服饰精品、设计品",
        "fonts": {"display": "Syne", "body": "Karla", "num": "Karla"},
        "display_weight": 700,
        "display_scale": 1.0,
        "display_tracking": "-0.03em",
        "radius": {"control": 0, "card": 0, "tile": 0, "button": 0},
        "border_w": 1,
        "banner": "solid",
        "light": {
            "surface": "#ffffff",
            "surface-alt": "#f3f3f3",
            "surface-raised": "#ffffff",
            "tile": "#eeeeee",
            "tile-alt": "#e2e2e2",
            "ink": "#0a0a0a",
            "ink-muted": "#5c5c5c",
            "rule": "#e4e4e4",
            "border": "#0a0a0a",
            "accent": "#0a0a0a",
            "demo": "#ff3b30",
            "on-demo": "#1a0000",
            "demo-soft": "#ffe3e1",
            "on-demo-soft": "#7a0f08",
            "demo-mark": "#d42a1f",
            "banner": "#0a0a0a",
            "banner-2": "#0a0a0a",
            "on-banner": "#ffffff",
            "footer": "#0a0a0a",
            "on-footer": "#ffffff",
        },
        "dark": {
            "surface": "#0a0a0a",
            "surface-alt": "#141414",
            "surface-raised": "#161616",
            "tile": "#1c1c1c",
            "tile-alt": "#262626",
            "ink": "#f5f5f5",
            "ink-muted": "#a6a6a6",
            "rule": "#262626",
            "border": "#f5f5f5",
            "accent": "#f5f5f5",
            "demo": "#ff5a50",
            "on-demo": "#1a0000",
            "demo-soft": "#3a1210",
            "on-demo-soft": "#ffc9c4",
            "demo-mark": "#ff7a72",
            "banner": "#f5f5f5",
            "banner-2": "#f5f5f5",
            "on-banner": "#0a0a0a",
            "footer": "#000000",
            "on-footer": "#f5f5f5",
        },
        "accents": [
            ("black", "Black", "#0a0a0a"),
            ("graphite", "Graphite", "#3a3a3a"),
            ("navy", "Navy", "#1b2a4a"),
            ("bottle", "Bottle green", "#1f4a38"),
        ],
    },
    {
        "id": "songket",
        "hero_shape": "999px 999px 0 0",
        "name": "Songket",
        "zh": "金线",
        "fit": "节庆礼品、高端",
        "fonts": {"display": "Cormorant", "body": "Mulish", "num": "Mulish"},
        "display_weight": 600,
        "display_scale": 1.3,
        "display_tracking": "0em",
        "radius": {"control": 2, "card": 4, "tile": 4, "button": 2},
        "border_w": 1,
        "banner": "solid",
        "light": {
            "surface": "#faf6f3",
            "surface-alt": "#f1e7e4",
            "surface-raised": "#ffffff",
            "tile": "#eddedb",
            "tile-alt": "#f3e6c4",
            "ink": "#2a0f14",
            "ink-muted": "#6b4b50",
            "rule": "#e8d9d6",
            "border": "#a08287",
            "accent": "#7a1628",
            "demo": "#c9a227",
            "on-demo": "#2a1d00",
            "demo-soft": "#f6ecc9",
            "on-demo-soft": "#5a4300",
            "demo-mark": "#86690a",
            "banner": "#7a1628",
            "banner-2": "#7a1628",
            "on-banner": "#f7e7b4",
            "footer": "#2a0f14",
            "on-footer": "#f3e3c0",
        },
        "dark": {
            "surface": "#170a0d",
            "surface-alt": "#200f13",
            "surface-raised": "#281418",
            "tile": "#311a1f",
            "tile-alt": "#33290f",
            "ink": "#f6e9e2",
            "ink-muted": "#c5a8ab",
            "rule": "#3a2126",
            "border": "#8a6a6f",
            "accent": "#e58a9b",
            "demo": "#e3c160",
            "on-demo": "#2a1d00",
            "demo-soft": "#362b10",
            "on-demo-soft": "#f7e6b0",
            "demo-mark": "#e3c160",
            "banner": "#4d0e1a",
            "banner-2": "#4d0e1a",
            "on-banner": "#f3dc9a",
            "footer": "#0e0507",
            "on-footer": "#f0dcc0",
        },
        "accents": [
            ("maroon", "Maroon", "#7a1628"),
            ("emerald", "Emerald", "#1a5a45"),
            ("royal", "Royal blue", "#2b2f7a"),
            ("black", "Black", "#1e1416"),
        ],
    },
    {
        "id": "litar",
        "hero_shape": "8px",
        "name": "Litar",
        "zh": "电路",
        "fit": "电子产品",
        "fonts": {"display": "Geist", "body": "Geist", "num": "Geist Mono"},
        "display_weight": 600,
        "display_scale": 1.0,
        "display_tracking": "-0.03em",
        "radius": {"control": 6, "card": 8, "tile": 8, "button": 6},
        "border_w": 1,
        "banner": "solid",
        "light": {
            "surface": "#f4f6f7",
            "surface-alt": "#e8edef",
            "surface-raised": "#ffffff",
            "tile": "#e1e7ea",
            "tile-alt": "#d5ecea",
            "ink": "#111a1f",
            "ink-muted": "#4f5d65",
            "rule": "#d9e0e3",
            "border": "#7d8a91",
            "accent": "#0d7d78",
            "demo": "#ffb020",
            "on-demo": "#231500",
            "demo-soft": "#fff0cf",
            "on-demo-soft": "#5a3a00",
            "demo-mark": "#9a6200",
            "banner": "#111a1f",
            "banner-2": "#111a1f",
            "on-banner": "#e8f4f3",
            "footer": "#111a1f",
            "on-footer": "#e3eaed",
        },
        "dark": {
            "surface": "#0b1114",
            "surface-alt": "#10181c",
            "surface-raised": "#152024",
            "tile": "#1a272c",
            "tile-alt": "#0f2f2d",
            "ink": "#e6eef1",
            "ink-muted": "#98a8af",
            "rule": "#22313a",
            "border": "#5b6d76",
            "accent": "#3fd3c8",
            "demo": "#ffb020",
            "on-demo": "#231500",
            "demo-soft": "#33260a",
            "on-demo-soft": "#ffe2a6",
            "demo-mark": "#ffb020",
            "banner": "#152024",
            "banner-2": "#152024",
            "on-banner": "#e6eef1",
            "footer": "#05090b",
            "on-footer": "#dbe5e9",
        },
        "accents": [
            ("teal", "Circuit teal", "#0d7d78"),
            ("violet", "Violet", "#5b3fd1"),
            ("red", "Signal red", "#c0342b"),
            ("graphite", "Graphite", "#2a343a"),
        ],
    },
]
